name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd exemples; make
    - name: make re
      run: cd exemples; make re
    - name: make clean
      run: cd exemples; make re ; make clean
    - name: make fclean
      run: cd exemples; make re ; make fclean
    - name: make test
      run: cd exemples; make re ; ./division_program 10 3 ; make fclean
    - name: install critérion
      run: sudo apt-get update; sudo apt-get install criterion*
    - name: check_program_compilation_test
      run: sudo apt-get install criterion* ; make re ; make tests_run ; make fclean


